name: daily_update
on: []
  #schedule:
  #  - cron: "30 10 * * *"

jobs:
  get-num-square:
    runs-on: ubuntu-latest
    name: Returns the number square
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v4.3.0
        with:
          python-version: 3.10.4
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests yagmail beautifulsoup4 argparse mako pyyaml
      - name: Pass Inputs to Shell
        run: |
          echo "GMAIL_AUTH=${{ secrets.GMAIL_SECRET }}"
      - name: execute py script # run file
        run: |
          python daily_update.py
