name: daily_update
on:
  schedule:
    - cron: "30 05 * * *"
  workflow_dispatch:
    
jobs:
  send_update_email:
    runs-on: ubuntu-latest
    name: Send Daily Update Email
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4.3.0
        with:
          python-version: 3.10.4
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests yagmail beautifulsoup4 argparse mako pyyaml
      - name: Fetch Secrets and Run daily_update.py
        env:
          GMAIL_SECRET: ${{ secrets.GMAIL_SECRET }}
          INFO_AUTH_USER: ${{ secrets.INFO_AUTH_USER }}
          INFO_AUTH_PASS: ${{ secrets.INFO_AUTH_PASS }}
          STRONG_KEY: ${{ secrets.STRONG_KEY }}
        run: |
          echo $GMAIL_SECRET > yagmail_auth.json
          python daily_update.py
          rm -f yagmail_auth.json
      - name: Push updates
        run: |
          git config --global user.name "guutz"
          git config --global user.email "findmagpie@gmail.com"
          git commit -a -m "daily update"
      
