name: snoogums
on:
  schedule:
    - cron: "*/5 * * * *"
  workflow_dispatch:
    
jobs:
  send_update_email:
    runs-on: ubuntu-latest
    name: Send Snoogums Email
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4.3.0
        with:
          python-version: 3.10.4
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install yagmail
          pip install arxiv
          pip install dateutil
      - name: Fetch Secrets and Run snoogums.py
        env:
          GMAIL_SECRET: ${{ secrets.GMAIL_SECRET }}
        run: |
          echo $GMAIL_SECRET > yagmail_auth.json
          python snoogums.py
          rm -f yagmail_auth.json
      - name: Add & Commit
        uses: EndBug/add-and-commit@v9.1.1
